CREATE TABLE IF NOT EXISTS `products` (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`key` CHAR(255) NOT NULL,
`source` VARCHAR(255) NOT NULL,
`dateUpdated` DATETIME NOT NULL,
`dateInserted` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
INDEX `dfkey` (`key`(30))
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;


