DROP TABLE IF EXISTS products;
CREATE TABLE IF NOT EXISTS `products` (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`key` TEXT NOT NULL,
`source` TEXT NOT NULL,
`date_updated` DATETIME NOT NULL,
`date_inserted` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
INDEX `dfkeyidx` (`key`(24))
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;


